language: python
python: 3.6.6
dist: trusty
sudo: true

install:
  - pip install -U pip setuptools wheel pip-tools

script:
  - pip-compile --no-annotate --no-header --upgrade --allow-unsafe test.in
  - cat test.txt
